package com.kriptobr.placar.tablet

/**
 * Idioma da interface e idioma da voz sao independentes.
 * E comum querer a tela em um e a chamada em outro, porque quem
 * precisa entender a contagem e quem esta jogando com voce.
 */
object Textos {

    const val EN = "en"
    const val PT = "pt"

    private val mapa = mapOf(
        EN to mapOf(
            "esquerda" to "LEFT",
            "direita" to "RIGHT",
            "sacador" to "SERVER",
            "saque_direita" to "SERVE RIGHT",
            "saque_esquerda" to "SERVE LEFT",
            "venceu" to "WINNER",
            "fim_game" to "GAME OVER",
            "ponto_de_jogo" to "GAME POINT",
            "desfazer" to "undo",
            "travado" to "locked, double tap to unlock",
            "aguardando" to "waiting for watch",
            "conectado" to "watch connected",
            "menu" to "Settings",
            "novo_game" to "New game",
            "inverter" to "Swap sides",
            "idioma_voz" to "Voice language",
            "idioma_tela" to "Screen language",
            "repetir" to "Repeat score",
            "fechar" to "Close",
            "quem_saca" to "Who serves first?",
            "confirmar_novo" to "Start a new game? The current score will be lost.",
            "sim" to "Yes",
            "nao" to "No",
            "voz_faltando" to "Voice not installed for this language. Install it in the Android settings, under Text to speech.",
            "jogadores" to "Players",
            "montar" to "Name the teams",
            "historico" to "Match history",
            "novo_jogador" to "Add player",
            "nome" to "Full name",
            "apelido" to "Short name",
            "email" to "Email",
            "sexo" to "Sex",
            "masculino" to "Male",
            "feminino" to "Female",
            "nao_informado" to "Not set",
            "foto" to "Photo",
            "escolher_foto" to "Choose from gallery",
            "tirar_foto" to "Take a photo",
            "salvar" to "Save",
            "excluir" to "Delete",
            "cancelar" to "Cancel",
            "escolher_jogador" to "Choose a player",
            "limpar" to "Clear",
            "sem_nome" to "Unnamed",
            "sem_jogadores" to "No players yet. Add the people you play with.",
            "sem_partidas" to "No matches saved yet.",
            "incompleta" to "unfinished",
            "resultado" to "Result",
            "enviar_email" to "Email the summary",
            "sem_email" to "No player has an email saved.",
            "sem_app_email" to "No email app found on this tablet.",
            "duracao" to "Duration",
            "minutos" to "min",
            "rallies" to "Total rallies",
            "rallies_ganhos" to "Rallies won",
            "rallies_recebendo" to "Rallies won while receiving",
            "turnos_secos" to "Service turns without scoring",
            "maior_sequencia" to "Longest point streak",
            "viradas" to "Lead changes",
            "voltar" to "Back",
            "iniciar_jogo" to "Start a game",
            "comecar" to "Start",
            "substituir" to "Substitute a player",
            "quem_sai" to "Who is leaving?",
            "quem_entra" to "Who is coming in?",
            "rodizio" to "Rotation",
            "presentes" to "Here today",
            "sugestao" to "Suggested next game",
            "aceitar" to "Use this",
            "sortear" to "Shuffle",
            "esperando" to "waiting",
            "rodadas" to "rounds",
            "precisa_quatro" to "Mark at least four people as here today.",
            "status" to "Status",
            "ultimo_contato" to "Last contact",
            "controle" to "Bluetooth control",
            "ultima_tecla" to "Last key",
            "saida_audio" to "Audio output",
            "alto_falante" to "Tablet speaker",
            "caixa_bluetooth" to "Bluetooth speaker",
            "ultima_partida" to "Last saved match",
            "endereco" to "Tablet address",
            "nunca" to "never",
            "disponivel" to "available",
            "indisponivel" to "not installed",
            "teste" to "Test mode",
            "aviso_teste" to "Nothing here is saved to the history.",
            "falar_en" to "Speak a score in English",
            "falar_pt" to "Speak a score in Portuguese",
            "capturar_tecla" to "Press a button on the control",
            "mapear_para" to "Assign this key to",
            "medir_tempo" to "Measure watch round trip",
            "derrubar" to "Drop the connection",
            "corrigir" to "Fix the score",
            "aplicar" to "Apply",
            "pontos_esq" to "Left points",
            "pontos_dir" to "Right points",
            "sacando_agora" to "Serving",
            "numero_sacador" to "Server number",
            "aviso_correcao" to "Fixing the score restarts the log from here, so undo will not go back past this point.",
            "estatisticas" to "Player stats",
            "vitorias" to "wins",
            "derrotas" to "losses",
            "aproveitamento" to "win rate",
            "parceiro_frequente" to "Most frequent partner",
            "melhor_parceiro" to "Best results with",
            "sem_dados" to "No finished matches yet.",
            "exportar" to "Export to CSV",
            "backup" to "Backup",
            "exportar_backup" to "Save a backup",
            "importar_backup" to "Restore from a backup",
            "aviso_backup" to "The backup holds players, photos, matches and rotation. Save it somewhere safe after you enter everyone. Restoring replaces what is on this tablet.",
            "backup_ok" to "Done.",
            "backup_erro" to "That file could not be read.",
            "dizer_side_out" to "Say \"side out\" on serve change",
            "ranking" to "Leaderboard",
            "hoje" to "Today",
            "sempre" to "All time",
            "email_sessao" to "Email today's summary",
            "jogos" to "games",
            "saldo" to "point diff",
            "sem_jogos_hoje" to "No games played today."
        ),
        PT to mapOf(
            "esquerda" to "ESQUERDA",
            "direita" to "DIREITA",
            "sacador" to "SACADOR",
            "saque_direita" to "SAQUE PELA DIREITA",
            "saque_esquerda" to "SAQUE PELA ESQUERDA",
            "venceu" to "VENCEU",
            "fim_game" to "FIM DE GAME",
            "ponto_de_jogo" to "PONTO DE JOGO",
            "desfazer" to "desfazer",
            "travado" to "travado, toque duas vezes para destravar",
            "aguardando" to "aguardando o relogio",
            "conectado" to "relogio conectado",
            "menu" to "Ajustes",
            "novo_game" to "Novo game",
            "inverter" to "Inverter lados",
            "idioma_voz" to "Idioma da voz",
            "idioma_tela" to "Idioma da tela",
            "repetir" to "Repetir o placar",
            "fechar" to "Fechar",
            "quem_saca" to "Quem saca primeiro?",
            "confirmar_novo" to "Comecar um novo game? O placar atual sera perdido.",
            "sim" to "Sim",
            "nao" to "Nao",
            "voz_faltando" to "Voz nao instalada para este idioma. Instale nas configuracoes do Android, em Conversao de texto em fala.",
            "jogadores" to "Jogadores",
            "montar" to "Definir as duplas",
            "historico" to "Historico de partidas",
            "novo_jogador" to "Novo jogador",
            "nome" to "Nome completo",
            "apelido" to "Nome curto",
            "email" to "E-mail",
            "sexo" to "Sexo",
            "masculino" to "Masculino",
            "feminino" to "Feminino",
            "nao_informado" to "Nao informado",
            "foto" to "Foto",
            "escolher_foto" to "Escolher da galeria",
            "tirar_foto" to "Tirar foto",
            "salvar" to "Salvar",
            "excluir" to "Excluir",
            "cancelar" to "Cancelar",
            "escolher_jogador" to "Escolher jogador",
            "limpar" to "Limpar",
            "sem_nome" to "Sem nome",
            "sem_jogadores" to "Nenhum jogador cadastrado. Cadastre quem joga com voce.",
            "sem_partidas" to "Nenhuma partida salva ainda.",
            "incompleta" to "incompleta",
            "resultado" to "Resultado",
            "enviar_email" to "Enviar resumo por e-mail",
            "sem_email" to "Nenhum jogador tem e-mail cadastrado.",
            "sem_app_email" to "Nenhum aplicativo de e-mail encontrado neste tablet.",
            "duracao" to "Duracao",
            "minutos" to "min",
            "rallies" to "Total de rallies",
            "rallies_ganhos" to "Rallies ganhos",
            "rallies_recebendo" to "Rallies ganhos recebendo",
            "turnos_secos" to "Turnos de saque sem pontuar",
            "maior_sequencia" to "Maior sequencia de pontos",
            "viradas" to "Viradas no placar",
            "voltar" to "Voltar",
            "iniciar_jogo" to "Iniciar um jogo",
            "comecar" to "Comecar",
            "substituir" to "Substituir jogador",
            "quem_sai" to "Quem esta saindo?",
            "quem_entra" to "Quem entra no lugar?",
            "rodizio" to "Rodizio",
            "presentes" to "Presentes hoje",
            "sugestao" to "Proximo jogo sugerido",
            "aceitar" to "Usar esta",
            "sortear" to "Sortear",
            "esperando" to "esperando",
            "rodadas" to "rodadas",
            "precisa_quatro" to "Marque pelo menos quatro pessoas como presentes.",
            "status" to "Status",
            "ultimo_contato" to "Ultimo contato",
            "controle" to "Controle Bluetooth",
            "ultima_tecla" to "Ultima tecla",
            "saida_audio" to "Saida de audio",
            "alto_falante" to "Alto-falante do tablet",
            "caixa_bluetooth" to "Caixa Bluetooth",
            "ultima_partida" to "Ultima partida salva",
            "endereco" to "Endereco do tablet",
            "nunca" to "nunca",
            "disponivel" to "disponivel",
            "indisponivel" to "nao instalada",
            "teste" to "Modo de teste",
            "aviso_teste" to "Nada aqui e gravado no historico.",
            "falar_en" to "Falar um placar em ingles",
            "falar_pt" to "Falar um placar em portugues",
            "capturar_tecla" to "Aperte um botao do controle",
            "mapear_para" to "Usar esta tecla para",
            "medir_tempo" to "Medir ida e volta do relogio",
            "derrubar" to "Derrubar a conexao",
            "corrigir" to "Corrigir o placar",
            "aplicar" to "Aplicar",
            "pontos_esq" to "Pontos da esquerda",
            "pontos_dir" to "Pontos da direita",
            "sacando_agora" to "Sacando",
            "numero_sacador" to "Numero do sacador",
            "aviso_correcao" to "Corrigir o placar reinicia o log a partir daqui, entao o desfazer nao volta alem deste ponto.",
            "estatisticas" to "Estatisticas por jogador",
            "vitorias" to "vitorias",
            "derrotas" to "derrotas",
            "aproveitamento" to "aproveitamento",
            "parceiro_frequente" to "Parceiro mais frequente",
            "melhor_parceiro" to "Melhores resultados com",
            "sem_dados" to "Nenhuma partida encerrada ainda.",
            "exportar" to "Exportar em CSV",
            "backup" to "Backup",
            "exportar_backup" to "Salvar um backup",
            "importar_backup" to "Restaurar de um backup",
            "aviso_backup" to "O backup guarda jogadores, fotos, partidas e rodizio. Guarde num lugar seguro depois de cadastrar todo mundo. Restaurar substitui o que esta neste tablet.",
            "backup_ok" to "Pronto.",
            "backup_erro" to "Nao foi possivel ler esse arquivo.",
            "dizer_side_out" to "Falar \"side out\" na troca de saque",
            "ranking" to "Ranking",
            "hoje" to "Hoje",
            "sempre" to "Sempre",
            "email_sessao" to "Enviar o resumo de hoje",
            "jogos" to "jogos",
            "saldo" to "saldo",
            "sem_jogos_hoje" to "Nenhum jogo hoje ainda."
        )
    )

    fun get(chave: String, idioma: String): String =
        mapa[idioma]?.get(chave) ?: mapa[EN]?.get(chave) ?: chave
}
